language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    
branches:
 only:
 - master

before_script:
 - chmod +x gradlew

script:
    - ./library/gradlew clean assemble test